f5e0dc = "ffbe91"
f2cdcd = "f0b4b4"
f5c2e7 = "f0aadd"
cba6f7 = "c198fd"
f38ba8 = "ff6c8d"
eba0ac = "ff8bb3"
fab387 = "ff9856"
f9e2af = "e9ad5b"
a6e3a1 = "90d05a"
94e2d5 = "41ddca"
89dceb = "00bcdb"
74c7ec = "5ed2ff"
89b4fa = "6ea3fe"
b4befe = "98a4f5"
cdd6f4 = "becaf9"
bac2de = "b5c9ff"
a6adc8 = "aabbe3"
9399b2 = "939ab7"
7f849c = "8087a2"
6c7086 = "6e738d"
585b70 = "5b6078"
45475a = "494d64"
313244 = "363a4f"
1e1e2e = "24273a"
181825 = "1e2030"
11111b = "181926"
F5E0DC = "FFBE91"
F2CDCD = "F0B4B4"
F5C2E7 = "F0AADD"
CBA6F7 = "C198FD"
F38BA8 = "FF6C8D"
EBA0AC = "FF8BB3"
FAB387 = "FF9856"
F9E2AF = "E9AD5B"
A6E3A1 = "90D05A"
94E2D5 = "41DDCA"
89DCEB = "00BCDB"
74C7EC = "5ED2FF"
89B4FA = "6EA3FE"
B4BEFE = "98A4F5"
CDD6F4 = "BECAF9"
BAC2DE = "B5C9FF"
A6ADC8 = "AABBE3"
9399B2 = "939AB7"
7F849C = "8087A2"
6C7086 = "6E738D"
585B70 = "5B6078"
45475A = "494D64"
1E1E2E = "24273A"
11111B = "181926"