pairs = [
["#f5e0dc","#FAA296"],
["#f2cdcd","#FFBAE2"],
["#f5c2e7","#FF9ED0"],
["#cba6f7","#C198FD"],
["#f38ba8","#FF6A7B"],
["#eba0ac","#FF7DAA"],
["#fab387","#FF9856"],
["#f9e2af","#E9AD5B"],
["#a6e3a1","#90D05A"],
["#94e2d5","#41DDCA"],
["#89dceb","#62E4FF"],
["#74c7ec","#05D1EC"],
["#89b4fa","#6EA3FE"],
["#b4befe","#8995FF"],
["#cdd6f4","#BECAF9"],
["#bac2de","#A7B1D9"],
["#a6adc8","#99A4CC"],
["#9399b2","#919ABA"],
["#7f849c","#8087A2"],
["#6c7086","#6E738D"],
["#585b70","#5B6078"],
["#45475a","#494D64"],
["#313244","#363A4F"],
["#1e1e2e","#24273A"],
["#181825","#1E2030"],
["#11111b","#181926"],
["mocha", "edo"]
]
case_sensitive = false
