pairs = [
["C97D6E","DE9D9D"],
["C98A7D","DEA89D"],
["BC76C1","B294BB"],
["8C6FAA","9D8BB8"],
["CB7676","CC6666"],
["CC8D82","C67D7D"],
["CC8D70","DE935F"],
["DCA466","F0C674"],
["4C8E72","B5BD68"],
["80A665","8ABEB7"],
["5EA994","95B3C9"],
["5D9AA9","7EA9B8"],
["6394BF","81A2BE"],
["6872AB","9DB5C9"],
["D8D6C9","C5C8C6"],
["B2B0A6","A8ABA9"],
["999895","8B8D8B"],
["7F7F7C","6F7271"],
["666666","5A5C5B"],
["4C4C4C","4D5057"],
["333333","3A3C3F"],
["1F1F1F","373B41"],
["181818","282A2E"],
["121212","1D1F21"],
["060606","161719"],
["000000","0F1011"],
]
# vit to tomorrow
case_sensitive = false
